name: Render CV PDF (A4)

on:
  workflow_dispatch:
  push:
    paths:
      - "dusan_vejnovic_cv_a4_purple_v22.html"
      - "tools/render-pdf.js"
      - ".github/workflows/render-pdf.yml"

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Render PDF with Puppeteer
        run: npm run render:pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: Dusan_Vejnovic_CV_A4
          path: dist/Dusan_Vejnovic_CV_A4.pdf
          if-no-files-found: error